# sleepinfo-clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sleepinfo-job-binding
subjects:
  - kind: ServiceAccount
    name: sleepinfo-job-sa
    namespace: kube-green
roleRef:
  kind: ClusterRole
  name: sleepinfo-job-clusterrole
  apiGroup: rbac.authorization.k8s.io
