apiVersion: v1
kind: ServiceAccount
metadata:
  name: sleepinfo-sa
  namespace: kube-green
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sleepinfo-cr
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces", "deployments", "daemonsets", "statefulsets", "replicasets", "jobs", "cronjobs"]
  verbs: ["get", "list"]
- apiGroups: ["kube-green.com"]
  resources: ["sleepinfos"]
  verbs: ["get", "create", "patch", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sleepinfo-crb
subjects:
- kind: ServiceAccount
  name: sleepinfo-sa
  namespace: kube-green
roleRef:
  kind: ClusterRole
  name: sleepinfo-cr
  apiGroup: rbac.authorization.k8s.io

